name: mh_base
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependency_overrides:
  vm_service: 14.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_ume_plus: ^4.1.0
  logger: ^2.5.0
  flutter_native_splash: ^2.3.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  dio: ^5.1.2
  fluttertoast: ^8.2.2
  go_router: ^12.1.3
  shared_preferences: ^2.1.1
  pinput: ^3.0.0
  smooth_page_indicator: ^1.1.0
  dropdown_search: ^5.0.6
  pretty_dio_logger: ^1.3.1
  flutter_easyloading: ^3.0.5
  async: ^2.11.0
  crypto: ^3.0.3
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.0.2
  badges: ^3.1.1
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.3.0
  path_provider: ^2.0.15
  photo_view: ^0.14.0
  google_sign_in: 6.2.1
  group_button: ^5.3.0
  flutter_facebook_auth: ^6.0.4
  fl_chart: ^0.66.2
  flutter_line_sdk:
    git:
      url: https://github.com/yxwandroid/flutter_line_sdk.git
      ref: master
  roundcheckbox: ^2.0.5
  dotted_border: ^2.0.0+3
  sensors_plus: ^3.1.0
  event_bus: ^2.0.0
  jpush_google_flutter: 1.0.7
  package_info: 2.0.2
  flutter_sound: 9.4.11
    #  jpush_google_flutter: 1.0.4
    #  jpush_flutter: 2.1.4
  firebase_core: 2.31.0
  firebase_analytics: 10.10.5
  firebase_crashlytics: 3.5.5
  firebase_performance: 0.9.4+5
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  camera: ^0.10.5+2
  share_plus: ^7.2.2
  wechat_assets_picker: ^9.0.0-dev.2
  decimal: ^2.3.3
  step_progress_indicator: ^1.0.2
  firebase_messaging: ^14.9.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.0
  url_launcher: ^6.1.14
  cached_network_image: ^3.3.0
  flutter_keyboard_visibility: ^5.4.1
  screenshot: 3.0.0
  flutter_slidable: ^3.0.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  photo_manager: ^3.0.0-dev.2
  month_picker_dialog: ^2.11.1
  video_thumbnail: ^0.5.3
  video_player: ^2.8.6
  numberpicker: ^2.1.2
  record: ^5.1.0
  audioplayers: ^6.0.0
  dropdown_button2: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_ume: ^1.0.1
  flutter_ume_kit_ui: ^1.0.0
  flutter_ume_kit_device: ^1.0.0
  flutter_ume_kit_perf: ^1.0.0
  flutter_ume_kit_show_code: ^1.0.0
  flutter_ume_kit_console: ^1.0.0
  flutter_ume_kit_dio: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
