name: mh_base
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependency_overrides:
  vm_service: 14.3.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.7.0
  fluttertoast: ^8.2.10
  go_router: ^14.7.2
  shared_preferences: ^2.5.1
  pinput: ^5.0.1
  smooth_page_indicator: ^1.2.0+3
  pretty_dio_logger: ^1.4.0
  flutter_easyloading: ^3.0.5
  async: ^2.11.0
  crypto: ^3.0.6
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  phone_numbers_parser: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_ume_plus: ^4.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
